base_url = "https://loic.truchot.dev"
title = "Loïc TRUCHOT Website"
default_language = "en"
highlight_code = true
highlight_theme = "one-dark"
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
	{ name = "categories", feed = true, paginate_by = 10 },
	{ name = "tags", fees = true, paginate_by = 10 },
]
languages = []
compile_sass = true
build_search_index = true
ignored_content = []
extra_syntaxes = []

[link_checker]
skip_prefixes = ["http://[2001:db8::]/"]
skip_anchor_prefixes = ["https://caniuse.com/"]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[translations]

[extra]
navbar_items = [
	{ url = "$BASE_URL/", name = "Home" },
	{ url = "$BASE_URL/blog", name = "Blog" },
	{ url = "$BASE_URL/podcasts", name = "Podcasts" },
	{ url = "$BASE_URL/videos", name = "Videos" },
	{ url = "$BASE_URL/cheatsheets", name = "Cheatsheets" },
	{ url = "$BASE_URL/tags", name = "Tags" }
]

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

[extra.author]
name = "Loïc TRUCHOT"
avatar = "/common/profil.jpeg"

[extra.social]
github = "ltruchot"
linkedin = "loïc-truchot-93924497"

[extra.analytics]
google = "UA-40583718-4"
